/Griffin/UseTIGRESSPositions true
/Griffin/addGriffinBack 16
/Projectile/A 18
/Projectile/Z 8
/Projectile/KE 48 MeV
/Projectile/Focus/X 0. mm
/Projectile/Focus/Y 0. mm
/Projectile/Focus/Z -50. mm
/Projectile/Focus/DX 0. mm
/Projectile/Focus/DY 0. mm
/Backing/Material G4_Au
/Backing/Thickness 14.9 um
/Backing/NStep 1
/Target/Material G4_C
/Target/Thickness 1.91 um
/Target/Report
/Target/NStep 1
/Reaction/AddDecay 1.274537 5.1937e-3
/Reaction/N_protons 0
/Reaction/N_neutrons 0
/Reaction/N_alpha 2
/CompoundFormation/Q 23.651 MeV
/CompoundFormation/CompoundExi 42.851 MeV
/ParticleEvaporation/Q1 -10.643 MeV
/ParticleEvaporation/Q2 -10.615 MeV
/ParticleEvaporation/Centroid 14.16082
/ParticleEvaporation/Width 1.001135
/ParticleEvaporation/Tau 2.286506
#/ParticleEvaporation/ConstrainAngularRange
#/ParticleEvaporation/MaxAngle 50.0 deg
/Results/Tree/CsIDetectorID 0
/Trigger/CsIDetectorID 0
/Trigger/A 4
/Trigger/Z 2
/Trigger/DefinedParticleCoincAndGamma
#/Trigger/DefinedParticleCoincAnd2GammaCores
/Trigger/DisableGriffin 1
/Trigger/DisableGriffin 2
/Trigger/DisableGriffin 3
/Trigger/DisableGriffin 4
/Trigger/DisableGriffinDetCol 9 2
/Trigger/DisableGriffinDetCol 12 2
/Trigger/CsIThreshold 3.0 MeV
#/Print/CsI_Track_Set
#/Print/Track_Set
#need to run this AFTER adjusting the target/backing parameters!
/Construction/TIPChamberZShift -0.0 mm
#/Print/Track_Set
/run/beamOn 1000000
/Results/Tree/Report
/Results/Tree/Save run1_1274only.root
/Projectile/Report
